# Generated by Django 5.2.5 on 2025-09-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('pk',), 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
