# Generated by Django 5.2.5 on 2025-09-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',), 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
