# Generated by Django 5.2.5 on 2025-09-11 19:59

import utils.image_tools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Título')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.favicon_upload_path, verbose_name='Favicon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.logo_upload_path, verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.banner_upload_path, verbose_name='Banner')),
                ('unknown_car', models.ImageField(blank=True, null=True, upload_to=utils.image_tools.unknown_car_upload_path, verbose_name='Carro Desconhecido')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Ex: 5562912345678 (Código do País + Código de Área + Número)', max_length=32, verbose_name='Número do Whatsapp')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
