# Generated by Django 5.2.5 on 2025-09-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='setup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de Contato'),
        ),
        migrations.AddField(
            model_name='setup',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Link do Facebook'),
        ),
        migrations.AddField(
            model_name='setup',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Link do Instagram'),
        ),
        migrations.AddField(
            model_name='setup',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Telefone Fixo'),
        ),
        migrations.AddField(
            model_name='setup',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Link do X/Twitter'),
        ),
    ]
