# Generated by Django 5.2.5 on 2025-09-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0002_setup_address_setup_email_setup_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição curta do site para SEO', verbose_name='Descrição do Site'),
        ),
    ]
