# Generated by Django 5.2.5 on 2025-09-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_setup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='header_subtitle',
            field=models.TextField(blank=True, help_text='O texto de apoio exibido abaixo do título principal.', verbose_name='Subtítulo do Header'),
        ),
        migrations.AddField(
            model_name='setup',
            name='header_title',
            field=models.CharField(blank=True, help_text='O título principal exibido na página inicial.', max_length=128, verbose_name='Título do header princial'),
        ),
    ]
