# Generated by Django 5.2.5 on 2025-09-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_setup_header_subtitle_setup_header_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='about',
            field=models.TextField(blank=True, help_text='Texto a ser exibido no footer.', verbose_name='Sobre'),
        ),
    ]
